# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainFinal.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QHBoxLayout,
    QHeaderView, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(909, 751)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.mainView = QLabel(self.centralwidget)
        self.mainView.setObjectName(u"mainView")
        self.mainView.setGeometry(QRect(10, 60, 580, 326))
        self.mainView.setFrameShape(QFrame.Box)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(320, 10, 261, 41))
        font = QFont()
        font.setFamilies([u"B Yekan"])
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 690, 891, 58))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.settingsButton = QPushButton(self.layoutWidget)
        self.settingsButton.setObjectName(u"settingsButton")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy1)
        icon = QIcon()
        icon.addFile(u"../icons/icons8-add-user-male-80.png", QSize(), QIcon.Normal, QIcon.Off)
        self.settingsButton.setIcon(icon)
        self.settingsButton.setIconSize(QSize(40, 40))

        self.horizontalLayout.addWidget(self.settingsButton)

        self.usersListButton = QPushButton(self.layoutWidget)
        self.usersListButton.setObjectName(u"usersListButton")
        sizePolicy1.setHeightForWidth(self.usersListButton.sizePolicy().hasHeightForWidth())
        self.usersListButton.setSizePolicy(sizePolicy1)
        self.usersListButton.setIcon(icon)
        self.usersListButton.setIconSize(QSize(40, 40))

        self.horizontalLayout.addWidget(self.usersListButton)

        self.enteriesListButton = QPushButton(self.layoutWidget)
        self.enteriesListButton.setObjectName(u"enteriesListButton")
        sizePolicy1.setHeightForWidth(self.enteriesListButton.sizePolicy().hasHeightForWidth())
        self.enteriesListButton.setSizePolicy(sizePolicy1)

        self.horizontalLayout.addWidget(self.enteriesListButton)

        self.stopButton = QPushButton(self.layoutWidget)
        self.stopButton.setObjectName(u"stopButton")
        sizePolicy1.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy1)

        self.horizontalLayout.addWidget(self.stopButton)

        self.startButton = QPushButton(self.layoutWidget)
        self.startButton.setObjectName(u"startButton")
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)

        self.horizontalLayout.addWidget(self.startButton)

        self.plate_permission_view = QLabel(self.centralwidget)
        self.plate_permission_view.setObjectName(u"plate_permission_view")
        self.plate_permission_view.setGeometry(QRect(600, 320, 300, 66))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.plate_permission_view.sizePolicy().hasHeightForWidth())
        self.plate_permission_view.setSizePolicy(sizePolicy2)
        self.plate_permission_view.setMaximumSize(QSize(300, 66))
        font1 = QFont()
        font1.setFamilies([u"B Yekan"])
        font1.setPointSize(18)
        self.plate_permission_view.setFont(font1)
        self.plate_permission_view.setAcceptDrops(False)
        self.plate_permission_view.setAutoFillBackground(False)
        self.plate_permission_view.setStyleSheet(u"background-color: rgb(51, 209, 122);")
        self.plate_permission_view.setFrameShape(QFrame.Box)
        self.plate_permission_view.setAlignment(Qt.AlignCenter)
        self.plate_owner_name_view = QLabel(self.centralwidget)
        self.plate_owner_name_view.setObjectName(u"plate_owner_name_view")
        self.plate_owner_name_view.setGeometry(QRect(600, 240, 300, 66))
        sizePolicy2.setHeightForWidth(self.plate_owner_name_view.sizePolicy().hasHeightForWidth())
        self.plate_owner_name_view.setSizePolicy(sizePolicy2)
        self.plate_owner_name_view.setMaximumSize(QSize(300, 66))
        self.plate_owner_name_view.setFont(font1)
        self.plate_owner_name_view.setFrameShape(QFrame.Box)
        self.plate_owner_name_view.setAlignment(Qt.AlignCenter)
        self.plate_view = QLabel(self.centralwidget)
        self.plate_view.setObjectName(u"plate_view")
        self.plate_view.setGeometry(QRect(600, 60, 300, 66))
        sizePolicy2.setHeightForWidth(self.plate_view.sizePolicy().hasHeightForWidth())
        self.plate_view.setSizePolicy(sizePolicy2)
        self.plate_view.setMaximumSize(QSize(300, 66))
        self.plate_view.setFrameShape(QFrame.Box)
        self.plate_view.setAlignment(Qt.AlignCenter)
        self.plateTextView = QLabel(self.centralwidget)
        self.plateTextView.setObjectName(u"plateTextView")
        self.plateTextView.setEnabled(True)
        self.plateTextView.setGeometry(QRect(600, 140, 300, 62))
        sizePolicy2.setHeightForWidth(self.plateTextView.sizePolicy().hasHeightForWidth())
        self.plateTextView.setSizePolicy(sizePolicy2)
        self.plateTextView.setMaximumSize(QSize(300, 62))
        font2 = QFont()
        font2.setFamilies([u"B Yekan"])
        font2.setPointSize(29)
        font2.setKerning(True)
        self.plateTextView.setFont(font2)
        self.plateTextView.setLayoutDirection(Qt.LeftToRight)
        self.plateTextView.setAutoFillBackground(False)
        self.plateTextView.setStyleSheet(u"")
        self.plateTextView.setFrameShape(QFrame.Box)
        self.plateTextView.setTextFormat(Qt.PlainText)
        self.plateTextView.setScaledContents(False)
        self.plateTextView.setAlignment(Qt.AlignCenter)
        self.tableWidget = QTableWidget(self.centralwidget)
        if (self.tableWidget.columnCount() < 3):
            self.tableWidget.setColumnCount(3)
        if (self.tableWidget.rowCount() < 15):
            self.tableWidget.setRowCount(15)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 400, 891, 281))
        font3 = QFont()
        font3.setFamilies([u"B Yekan"])
        self.tableWidget.setFont(font3)
        self.tableWidget.setLayoutDirection(Qt.RightToLeft)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.plate_text_ir = QLabel(self.centralwidget)
        self.plate_text_ir.setObjectName(u"plate_text_ir")
        self.plate_text_ir.setEnabled(True)
        self.plate_text_ir.setGeometry(QRect(830, 140, 71, 62))
        sizePolicy2.setHeightForWidth(self.plate_text_ir.sizePolicy().hasHeightForWidth())
        self.plate_text_ir.setSizePolicy(sizePolicy2)
        self.plate_text_ir.setMaximumSize(QSize(300, 62))
        font4 = QFont()
        font4.setFamilies([u"B Yekan"])
        font4.setPointSize(23)
        font4.setKerning(True)
        self.plate_text_ir.setFont(font4)
        self.plate_text_ir.setLayoutDirection(Qt.LeftToRight)
        self.plate_text_ir.setAutoFillBackground(False)
        self.plate_text_ir.setStyleSheet(u"letter-spacing: 3px;\n"
"                        padding-bottom: 3%;\n"
"                    ")
        self.plate_text_ir.setFrameShape(QFrame.NoFrame)
        self.plate_text_ir.setTextFormat(Qt.PlainText)
        self.plate_text_ir.setScaledContents(False)
        self.plate_text_ir.setAlignment(Qt.AlignCenter)
        self.plate_text_num = QLabel(self.centralwidget)
        self.plate_text_num.setObjectName(u"plate_text_num")
        self.plate_text_num.setEnabled(True)
        self.plate_text_num.setGeometry(QRect(630, 140, 201, 62))
        sizePolicy2.setHeightForWidth(self.plate_text_num.sizePolicy().hasHeightForWidth())
        self.plate_text_num.setSizePolicy(sizePolicy2)
        self.plate_text_num.setMaximumSize(QSize(300, 62))
        font5 = QFont()
        font5.setFamilies([u"B Yekan"])
        font5.setPointSize(28)
        font5.setKerning(True)
        self.plate_text_num.setFont(font5)
        self.plate_text_num.setLayoutDirection(Qt.LeftToRight)
        self.plate_text_num.setAutoFillBackground(False)
        self.plate_text_num.setStyleSheet(u"letter-spacing: 3px;\n"
"                        padding-bottom: 5%;\n"
"                    ")
        self.plate_text_num.setFrameShape(QFrame.NoFrame)
        self.plate_text_num.setTextFormat(Qt.PlainText)
        self.plate_text_num.setScaledContents(False)
        self.plate_text_num.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(610, 10, 31, 41))
        self.label_2.setFont(font)
        self.label_2.setPixmap(QPixmap(u"../icons/65th_xs.png"))
        self.label_2.setScaledContents(True)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(270, 10, 31, 41))
        self.label_3.setFont(font)
        self.label_3.setPixmap(QPixmap(u"../icons/65th_xs.png"))
        self.label_3.setScaledContents(True)
        self.gv = QGraphicsView(self.centralwidget)
        self.gv.setObjectName(u"gv")
        self.gv.setGeometry(QRect(10, 60, 581, 331))
        self.gv.setFrameShape(QFrame.Panel)
        self.gv.setFrameShadow(QFrame.Plain)
        MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.startButton, self.stopButton)
        QWidget.setTabOrder(self.stopButton, self.enteriesListButton)
        QWidget.setTabOrder(self.enteriesListButton, self.usersListButton)
        QWidget.setTabOrder(self.usersListButton, self.settingsButton)
        QWidget.setTabOrder(self.settingsButton, self.tableWidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"SmartResidentGuard", None))
        self.mainView.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"SmartResidentGuard", None))
#if QT_CONFIG(tooltip)
        self.settingsButton.setToolTip(QCoreApplication.translate("MainWindow", u"Settings", None))
#endif // QT_CONFIG(tooltip)
        self.settingsButton.setText("")
#if QT_CONFIG(tooltip)
        self.usersListButton.setToolTip(QCoreApplication.translate("MainWindow", u"List of residents", None))
#endif // QT_CONFIG(tooltip)
        self.usersListButton.setText("")
#if QT_CONFIG(tooltip)
        self.enteriesListButton.setToolTip(QCoreApplication.translate("MainWindow", u"Traffic list", None))
#endif // QT_CONFIG(tooltip)
        self.enteriesListButton.setText("")
#if QT_CONFIG(tooltip)
        self.stopButton.setToolTip(QCoreApplication.translate("MainWindow", u"to stop", None))
#endif // QT_CONFIG(tooltip)
        self.stopButton.setText("")
#if QT_CONFIG(tooltip)
        self.startButton.setToolTip(QCoreApplication.translate("MainWindow", u"Start", None))
#endif // QT_CONFIG(tooltip)
        self.startButton.setText("")
        self.plate_permission_view.setText("")
        self.plate_owner_name_view.setText("")
        self.plate_view.setText("")
        self.plateTextView.setText("")
        self.plate_text_ir.setText("")
        self.plate_text_num.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
    # retranslateUi

